export const Logos = [
  { name: "Typescript", icon: "SiTypescript" },
  { name: "Javascript", icon: "SiJavascript" },
  { name: "bash", icon: "SiGnubash" },
  { name: "Sql", icon: "TbSql" },
  { name: "React", icon: "SiReact" },
  { name: "Next.js", icon: "SiNextdotjs" },
  { name: "Remix", icon: "SiRemix" },
  { name: "Redux", icon: "SiRedux" },
  { name: "Sass", icon: "SiSass" },
  { name: "Css", icon: "SiCss3" },
  { name: "Tailwind", icon: "SiTailwindcss" },
  { name: "node.js", icon: "SiNodedotjs" },
  { name: "express", icon: "SiExpress" },
  { name: "docker", icon: "SiDocker" },
  { name: "MySQL", icon: "SiMysql" },
  { name: "MongoDB", icon: "SiMongodb" },
  { name: "PostgreSQL", icon: "SiPostgresql" },
  { nam: "Postman", icon: "SiPostman" },
];
