export const Logos = [
  {
    name: "Typescript",
    icon: "SiTypescript",
    badge: "badges-typescript",
    color: "color-typescript",
  },
  {
    name: "Javascript",
    icon: "SiJavascript",
    badge: "badges-js",
    color: "color-js",
  },
  {
    name: "bash",
    icon: "SiGnubash",
    badge: "badges-bash",
    color: "color-bash",
  },
  { name: "Sql", icon: "TbSql", badge: "badges-sql", color: "color-sql" },
  {
    name: "React",
    icon: "SiReact",
    badge: "badges-react",
    color: "color-react",
  },
  {
    name: "Next.js",
    icon: "SiNextdotjs",
    badge: "badges-next",
    color: "color-next",
  },
  {
    name: "Remix",
    icon: "SiRemix",
    badge: "badges-remix",
    color: "color-remix",
  },
  {
    name: "Redux",
    icon: "SiRedux",
    badge: "badges-redux",
    color: "color-redux",
  },
  { name: "Sass", icon: "SiSass", badge: "badges-sass", color: "color-sass" },
  { name: "Css", icon: "SiCss3", badge: "badges-css", color: "color-css" },
  {
    name: "Tailwind",
    icon: "SiTailwindcss",
    badge: "badges-tailwind",
    color: "color-tailwind",
  },
  {
    name: "node.js",
    icon: "SiNodedotjs",
    badge: "badges-node",
    color: "color-node",
  },
  {
    name: "express",
    icon: "SiExpress",
    badge: "badges-express",
    color: "color-express",
  },
  {
    name: "docker",
    icon: "SiDocker",
    badge: "badges-docker",
    color: "color-docker",
  },
  {
    name: "MySQL",
    icon: "SiMysql",
    badge: "badges-mysql",
    color: "color-mysql",
  },
  {
    name: "MongoDB",
    icon: "SiMongodb",
    badge: "badges-mongo",
    color: "color-mongo",
  },
  {
    name: "PostgreSQL",
    icon: "SiPostgresql",
    badge: "badges-postgres",
    color: "color-postgres",
  },
  {
    name: "Prisma",
    icon: "SiPrisma",
    badge: "badges-prisma",
    color: "color-prisma",
  },
  {
    name: "Mongoose",
    icon: "SiMongoose",
    badge: "badges-mongoose",
    color: "color-mongoose",
  },
  {
    nam: "Postman",
    icon: "SiPostman",
    badge: "badges-postman",
    color: "color-postman",
  },
];
